apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-quarkus-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-quarkus-app
    app.kubernetes.io/part-of: test-app-165779292
  name: code-quarkus-app
  namespace: rorai
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: code-quarkus-app
status:
  loadBalancer: {}
